name: build_package_x86_22.04

on:
  push:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *
              
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ruby-dev python3 python3-pip libzmq3-dev libgtk-3-dev libelf-dev libjna-jni default-jdk nodejs npm libzmq-jni libzmq5 build-essential
          sudo pip3 install cython
          sudo gem install fpm
          
      - name: Build with make
        run: |
          mkdir -p /tmp/zcm
          ./waf configure --use-all --prefix=/tmp/zcm      
          ./waf build
          sudo ./waf install
          ls -a /tmp/zcm
          VERSION="1.1.5-$(date +'%m/%d/%Y')"
          VERSION=$(echo "$VERSION" | sed 's/\//-/g')
          fpm -a x86_64 -s dir -t deb -n zcm -v "$VERSION" -C /tmp/zcm -p zcm_VERSION_ARCH.deb -d "dbus-x11"

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "zcm"
          path: |
            *.deb
            *.log
          if-no-files-found: error

      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "ubuntu"
          release: "jammy"
          republish: "true" # needed ONLY if version is not changing
          file: "*.deb"
