name: build_package_x86_22.04

on:
  push:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *
              
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip libzmq-dev build-essential
          sudo pip3 install cython
          
      - name: Build with make
        run: |
          ./waf configure --use-all          
          ./waf build
          sudo ./waf install
          ls -a

      # - name: Upload to Github
      #   uses: 'actions/upload-artifact@v2'
      #   with:
      #     name: "OpenHD"
      #     path: |
      #       *.deb
      #       *.log
      #     if-no-files-found: error

      # - name: Push
      #   id: push
      #   uses: cloudsmith-io/action@master
      #   with:
      #     api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
      #     command: "push"
      #     format: "deb"
      #     owner: "openhd"
      #     repo: ${{ github.ref_name }}
      #     distro: "ubuntu"
      #     release: "jammy"
      #     republish: "true" # needed ONLY if version is not changing
      #     file: "*.deb"
      #   if: ${{ github.ref != 'refs/heads/2.5-evo' }}
